# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
one = Article.create content: "First ipsum dolor sit amet, consectetur adipiscing elit. Cras vulputate tempor eleifend. Praesent eget sapien neque. Quisque viverra rutrum dui, id convallis tellus vehicula et. Phasellus accumsan suscipit finibus. Vestibulum ut ligula mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla blandit dui et risus facilisis rhoncus. Quisque dapibus lacinia nulla vel accumsan. Morbi ultricies enim ante, eget bibendum dui aliquet id. Nam sed metus nec elit rutrum ultrices in nec metus. Suspendisse et nulla leo. Nunc dignissim dolor et posuere vestibulum. Sed tristique diam vel leo aliquet ultrices. Integer semper dapibus nisl, luctus pulvinar justo rutrum at. Morbi ut dapibus magna. Pellentesque lectus ex, blandit sed fringilla eu, convallis ut eros."
two = Article.create content: "Second neque ipsum, malesuada ac accumsan vel, euismod eu lorem. Aenean consectetur diam et sem euismod eleifend. Donec quis sollicitudin ante. Curabitur id orci at arcu molestie euismod. Duis pellentesque, lectus in fermentum vulputate, libero leo ullamcorper dolor, id faucibus risus lectus in libero. Fusce erat justo, semper eu dapibus et, accumsan fermentum nulla. Nunc vel aliquam eros. Curabitur quis molestie nisi. Praesent sed ipsum sed quam dignissim hendrerit. Aenean nec sodales metus. Proin nec orci viverra, molestie odio sit amet, efficitur sem. Donec sodales magna quis volutpat rhoncus. Nunc eu ipsum est. Phasellus nunc urna, consequat at faucibus quis, scelerisque vitae lectus. Mauris lorem urna, imperdiet et tristique ut, suscipit nec augue."
three = Article.create content: "Third ac rhoncus orci, malesuada tempus velit. Vestibulum massa tellus, auctor eget sodales nec, tempor nec libero. Vestibulum tincidunt vestibulum porttitor. Duis consectetur fermentum urna at tempor. Duis id tortor eu leo dignissim varius non venenatis diam. Integer eget lorem lacus. Suspendisse vel mauris in justo fringilla venenatis. Praesent rutrum mi malesuada nisl venenatis, a bibendum ipsum pellentesque. Mauris sit amet mi ut est semper suscipit sed sit amet ipsum. Quisque sagittis et ante et tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis augue velit, tristique eget ante eu, vulputate porta nibh. Sed luctus ultricies ligula, quis laoreet libero rutrum eu."
four = Article.create content: "Fourth non elementum dolor, sit amet pulvinar odio. Donec sagittis ac dolor a porttitor. Etiam in odio nec urna blandit suscipit non ac nunc. Nulla felis mi, pretium ut ornare vitae, laoreet sed est. Duis efficitur, arcu vel consequat blandit, nibh purus tristique elit, vel cursus tortor quam sed dui. Vestibulum scelerisque eros eget volutpat malesuada. Nam nec erat pellentesque lacus iaculis pharetra quis nec augue. Aliquam elementum sollicitudin sem id vehicula. Nullam sodales dui sit amet volutpat volutpat. Vestibulum malesuada massa quis dui consequat tincidunt. Vestibulum convallis neque nec purus feugiat suscipit. Sed sollicitudin convallis felis, a vestibulum sapien"
five = Article.create content: "Last vel augue consectetur, feugiat sem non, luctus elit. Fusce ut risus a magna varius bibendum et vitae lacus. Quisque ac magna sagittis arcu efficitur lobortis. Integer sed neque est. Integer vestibulum consequat leo quis elementum. Nunc id tellus at nibh fermentum tincidunt. Vestibulum aliquam quam eget varius finibus. Morbi ante sem, rhoncus id dui id, posuere rhoncus massa. Cras dolor neque, ornare ut bibendum sed, fringilla vitae tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla quis auctor arcu, eu imperdiet orci. Phasellus sed mauris quis risus convallis eleifend. Proin metus nisl, eleifend ac pellentesque id, porta a lacus. Vivamus turpis velit, dapibus eget purus et, bibendum mollis est. Nunc fringilla, lorem sit amet vehicula laoreet, magna quam imperdiet risus, at vehicula arcu ipsum non mi. Nulla iaculis leo a nisi imperdiet, vel congue lacus mollis."
